---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Deploy NGINX config from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  become: yes

- name: Ensure NGINX is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes
